# Generated by Django 3.1.2 on 2020-10-25 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('format_paper', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(max_length=20)),
            ],
            options={
                'verbose_name': 'Бумага',
                'verbose_name_plural': 'Бумаги',
            },
        ),
        migrations.CreateModel(
            name='Print_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price_if_before_1000', models.FloatField(max_length=20)),
                ('price_if_after_1000', models.FloatField(max_length=20)),
                ('price_form_print', models.FloatField(max_length=20)),
            ],
            options={
                'verbose_name': 'Печать бамагу',
                'verbose_name_plural': 'Печати бумаг',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, null=True)),
                ('client_phone', models.CharField(max_length=100, null=True)),
                ('client_company', models.CharField(max_length=200, null=True)),
                ('count', models.IntegerField(default=1)),
                ('total_price', models.FloatField(blank=True, default=True, max_length=20, null=True)),
                ('price_for_one', models.FloatField(blank=True, default=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('format_p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.format')),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.paper')),
                ('print_paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.print_paper')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
