# Generated by Django 3.1.2 on 2020-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Format',
            new_name='Devision',
        ),
        migrations.AlterModelOptions(
            name='devision',
            options={'verbose_name': 'Деление', 'verbose_name_plural': 'Деление'},
        ),
        migrations.RenameField(
            model_name='devision',
            old_name='format_paper',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='format_p',
            new_name='devision_paper',
        ),
        migrations.AddField(
            model_name='paper',
            name='format_paper',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
